### ISSUE TITLE
配置环境出错的问题

### ISSUE THREAD

**Issue by JunyuanDeng** [skhu101/ConsistentNeRF#1]
您好，我在配置环境的时候出现了写问题：
一个是在regnerf里面，配置完成之后出现
```
(regnerf) juneyoung@juneyoung:~/Programmes/ConsistentNeRF/RegNeRF$ CUDA_VISIBLE_DEVICES=0 python train.py --gin_configs configs/regnerf3/llff/room3.gin 
I1010 11:52:53.366230 139984956004160 tpu_client.py:54] Starting the local TPU driver.
I1010 11:52:53.366422 139984956004160 xla_bridge.py:226] Unable to initialize backend 'tpu_driver': Not found: Unable to find driver in registry given worker: local://
I1010 11:52:53.413939 139984956004160 xla_bridge.py:226] Unable to initialize backend 'tpu': Invalid argument: TpuPlatform is not available.
2023-10-10 11:52:53.516892: W external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:231] Falling back to the CUDA driver for PTX compilation; ptxas does not support CC 8.9
2023-10-10 11:52:53.516911: W external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:234] Used ptxas at ptxas
2023-10-10 11:52:53.517249: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:625] failed to get PTX kernel "shift_right_logical_3" from module: CUDA_ERROR_NOT_FOUND: named symbol not found
2023-10-10 11:52:53.517266: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2036] Execution of replica 0 failed: Internal: Could not find the corresponding function
Traceback (most recent call last):
  File "train.py", line 573, in <module>
    app.run(main)
  File "/home/juneyoung/anaconda3/envs/regnerf/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/juneyoung/anaconda3/envs/regnerf/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "train.py", line 299, in main
    rng = random.PRNGKey(20200823)
  File "/home/juneyoung/anaconda3/envs/regnerf/lib/python3.7/site-packages/jax/_src/random.py", line 75, in PRNGKey
    k1 = convert(lax.shift_right_logical(seed_arr, lax._const(seed_arr, 32)))
  File "/home/juneyoung/anaconda3/envs/regnerf/lib/python3.7/site-packages/jax/_src/lax/lax.py", line 382, in shift_right_logical
    return shift_right_logical_p.bind(x, y)
  File "/home/juneyoung/anaconda3/envs/regnerf/lib/python3.7/site-packages/jax/core.py", line 264, in bind
    out = top_trace.process_primitive(self, tracers, params)
  File "/home/juneyoung/anaconda3/envs/regnerf/lib/python3.7/site-packages/jax/core.py", line 603, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/juneyoung/anaconda3/envs/regnerf/lib/python3.7/site-packages/jax/interpreters/xla.py", line 249, in apply_primitive
    return compiled_fun(*args)
  File "/home/juneyoung/anaconda3/envs/regnerf/lib/python3.7/site-packages/jax/interpreters/xla.py", line 365, in _execute_compiled_primitive
    out_bufs = compiled.execute(input_bufs)
RuntimeError: Internal: Could not find the corresponding function
```
另一个是配置pytorch1.8_skhu.yaml出现的：
```
(regnerf) juneyoung@juneyoung:~/Programmes/ConsistentNeRF/nerf-pytorch-master$ conda env create -f pytorch1.8_skhu.yaml
Collecting package metadata (repodata.json): / WARNING conda.models.version:get_matcher(556): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.9.0.*, but conda is ignoring the .* and treating it as 1.9.0
WARNING conda.models.version:get_matcher(556): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.6.0.*, but conda is ignoring the .* and treating it as 1.6.0
WARNING conda.models.version:get_matcher(556): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.7.1.*, but conda is ignoring the .* and treating it as 1.7.1
WARNING conda.models.version:get_matcher(556): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.8.0.*, but conda is ignoring the .* and treating it as 1.8.0
done
Solving environment: failed

ResolvePackageNotFound: 
  - jpeg==9b=0
  - torchaudio==0.8.0=py37
  - ffmpeg==4.3=hf484d3e_0
  - pytorch==1.8.0=py3.7_cuda10.1_cudnn7.6.3_0
```
您知道是什么问题吗

**Comment by yklInverted** [comment]
您好，第一个报错应该是cuda与jaxlib的版本匹配问题，可以尝试更新cuda到适配的版本，如：
`conda install cudatoolkit=11.0`

关于第二个问题您可以尝试在yaml中去掉对应package版本号后的detail，如：

```
dependencies:
  - jpeg==9b
  - torchaudio==0.8.0
  - ffmpeg==4.3
  - pytorch==1.8.0

```
如果前三个package还有问题的话只用保留 pytorch 即可。

**Comment by JunyuanDeng** [comment]
第一个问题我用了一个全新的环境，现在可以跑了。还有一个问题想问问，您提到And then copy the 'data' folder from our backup data here, which contains。这个我没找到link，这个方便提供吗？

第二个问题还是没解决，出现了很多不匹配的结果：
```
(base) juneyoung@juneyoung:~/Programmes/ConsistentNeRF/nerf-pytorch-master$ conda env create -f pytorch1.8_skhu.yaml
Collecting package metadata (repodata.json): \ WARNING conda.models.version:get_matcher(556): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.7.1.*, but conda is ignoring the .* and treating it as 1.7.1
WARNING conda.models.version:get_matcher(556): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.9.0.*, but conda is ignoring the .* and treating it as 1.9.0
WARNING conda.models.version:get_matcher(556): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.8.0.*, but conda is ignoring the .* and treating it as 1.8.0
WARNING conda.models.version:get_matcher(556): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.6.0.*, but conda is ignoring the .* and treating it as 1.6.0
done
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                 \  
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                 -  

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package libsqlite conflicts for:
parso==0.8.3=pyhd3eb1b0_0 -> python[version='>=3.6'] -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
rsa==4.7.2=pyhd3eb1b0_1 -> python -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
aiosignal==1.2.0=pyhd3eb1b0_0 -> python[version='>=3.6'] -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
pyasn1-modules==0.2.8=py_0 -> python -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
cachetools==4.2.2=pyhd3eb1b0_0 -> python[version='>=3.5'] -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
python==3.7.6=h0371630_2 -> sqlite[version='>=3.30.1,<4.0a0'] -> libsqlite[version='3.39.2|3.39.3|3.39.4|3.40.0|3.40.0|3.41.2|3.42.0|3.43.0|3.43.2',build='h2797004_1|h2797004_0|h753d276_1|h753d276_0|h753d276_0|h753d276_0|h753d276_1']
wheel==0.36.2=pyhd3eb1b0_0 -> python -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
pyopenssl==21.0.0=pyhd3eb1b0_1 -> python -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
charset-normalizer==2.0.4=pyhd3eb1b0_0 -> python[version='>=3.5'] -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
urllib3==1.26.7=pyhd3eb1b0_0 -> python[version='>=3.6,<4.0'] -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
werkzeug==2.0.2=pyhd3eb1b0_0 -> python[version='>=3.6'] -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
tensorboard==2.6.0=py_1 -> python[version='>=3.2'] -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
google-auth-oauthlib==0.4.1=py_2 -> python -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
attrs==21.2.0=pyhd3eb1b0_0 -> python -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
pygments==2.10.0=pyhd3eb1b0_0 -> python[version='>=3.6'] -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
filelock==3.0.12=pyhd3eb1b0_1 -> python -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
click==8.0.3=pyhd3eb1b0_0 -> python[version='>=3.6'] -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
oauthlib==3.1.1=pyhd3eb1b0_0 -> python[version='>=3.6'] -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
idna==3.3=pyhd3eb1b0_0 -> python[version='>=3.5'] -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
requests==2.26.0=pyhd3eb1b0_0 -> python[version='>=3.6'] -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
wcwidth==0.2.5=pyhd3eb1b0_0 -> python -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
argcomplete==1.12.3=pyhd3eb1b0_0 -> python[version='>=3.5'] -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
backcall==0.2.0=pyhd3eb1b0_0 -> python -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
matplotlib-inline==0.1.2=pyhd3eb1b0_2 -> python[version='>=3.6'] -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
asynctest==0.13.0=py_0 -> python[version='>=3.4'] -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
pickleshare==0.7.5=pyhd3eb1b0_1003 -> python[version='>=3'] -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
tensorboard-plugin-wit==1.6.0=py_0 -> python[version='>=3'] -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
traitlets==5.1.1=pyhd3eb1b0_0 -> python[version='>=3.7'] -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
decorator==5.1.0=pyhd3eb1b0_0 -> python -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
google-auth==1.33.0=pyhd3eb1b0_0 -> python[version='>=3.6'] -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
jupyter_client==6.1.12=pyhd3eb1b0_0 -> python[version='>=3.5'] -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
dataclasses==0.8=pyh6d0b6a4_7 -> python[version='>=3.7'] -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
pycparser==2.21=pyhd3eb1b0_0 -> python[version='>=3.6'] -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
requests-oauthlib==1.3.0=py_0 -> python -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
ipython_genutils==0.2.0=pyhd3eb1b0_1 -> python -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
pyasn1==0.4.8=pyhd3eb1b0_0 -> python -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
pytorch=1.8.0 -> python[version='>=3.9,<3.10.0a0'] -> libsqlite[version='>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0']
zipp==3.6.0=pyhd3eb1b0_0 -> python[version='>=3.6'] -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
prompt-toolkit==3.0.20=pyhd3eb1b0_0 -> python -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
async-timeout==4.0.1=pyhd3eb1b0_0 -> python[version='>=3.6'] -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
pexpect==4.8.0=pyhd3eb1b0_3 -> python -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']
ptyprocess==0.7.0=pyhd3eb1b0_2 -> python -> libsqlite[version='>=3.39.2,<4.0a0|>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0|>=3.43.0,<4.0a0|>=3.41.2,<4.0a0']

Package libgcc-ng conflicts for:
urllib3==1.26.7=pyhd3eb1b0_0 -> brotlipy[version='>=0.6.0'] -> libgcc-ng[version='>=10.3.0|>=11.2.0|>=7.3.0|>=7.5.0|>=12|>=9.4.0|>=9.3.0|>=4.9|>=7.2.0']
sqlite==3.33.0=h62c20be_0 -> libedit[version='>=3.1.20191231,<3.2.0a0'] -> libgcc-ng[version='>=10.3.0|>=11.2.0|>=7.5.0|>=12|>=9.4.0|>=7.2.0|>=4.9']
frozenlist==1.2.0=py37h7f8727e_0 -> libgcc-ng[version='>=7.5.0']
pyopenssl==21.0.0=pyhd3eb1b0_1 -> cryptography[version='>=3.3'] -> libgcc-ng[version='>=10.3.0|>=12|>=7.3.0|>=9.4.0|>=9.3.0|>=11.2.0|>=7.5.0|>=7.2.0|>=4.9']
backcall==0.2.0=pyhd3eb1b0_0 -> python -> libgcc-ng[version='>=10.3.0|>=11.2.0|>=7.5.0|>=7.3.0|>=7.2.0|>=12|>=9.4.0|>=9.3.0|>=4.9']
cffi==1.15.0=py37h7f8727e_0 -> libgcc-ng[version='>=7.5.0']
tk==8.6.10=hbc83047_0 -> zlib[version='>=1.2.11,<1.3.0a0'] -> libgcc-ng[version='>=10.3.0|>=11.2.0|>=7.5.0|>=7.2.0|>=12|>=4.9']
google-auth-oauthlib==0.4.1=py_2 -> python -> libgcc-ng[version='>=10.3.0|>=11.2.0|>=7.5.0|>=7.3.0|>=7.2.0|>=12|>=9.4.0|>=9.3.0|>=4.9']
mkl-service==2.4.0=py37h7f8727e_0 -> python[version='>=3.7,<3.8.0a0'] -> libgcc-ng[version='>=11.2.0|>=7.3.0|>=7.2.0|>=9.4.0|>=9.3.0|>=4.9']
jpeg=9b -> libgcc-ng[version='>=7.2.0']
...
```
这个原因是为什么呢？

**Comment by yklInverted** [comment]
您好，关于第一个问题，非常抱歉，我们的数据目前在公司系统内部，发布需要一些审核流程，我们会尽快提供！目前若是尝试baseline模型，您可以参照regnerf原文下载数据[https://github.com/google-research/google-research/tree/master/regnerf](url)；对于nerf-pytorch-master，您可以参照nerf原文下载数据[https://github.com/bmild/nerf/tree/master](url)及使用相应config文件。

关于第二个问题，原本上传的环境不只用于该模型，有些冗余的package，我上传了一个新的环境配置文件environment.yml，您可以使用新的文件配置环境。
